### PR TITLE
feat: Chinese(zh-Hans) translation to fastlane metadata

### PR DESCRIPTION
**Pull request by BackMountainDevil**
supplement for https://github.com/jd1378/otphelper/pull/13. Sorry to leak the part of them. Language tested on my phone with LineageOS 20. But I can not test the fastlane metadata.

I see otphelper/fastlane/metadata/android/en-US/images/phoneScreenshots and otphelper/fastlane/metadata/android/de/images/phoneScreenshots. So I think I should add 2 images. However, you said you will do some changes to the component. Thus, I do not upload the images. If needed, I am happy to help.

### CODE REVIEW

**Comment by jd1378** [comment]
Hi
No need to add images, i need to create them myself 
I'll check this later today and merge 

title.txt is the app title/name shown on fdroid or google play, please make sure it is consistent with the name of the app from #13

**Comment by BackMountainDevil** [comment]
Thanks for your careful review. A new PR will replace this bad PRThanks for your careful review. A new PR will replace this bad PR

**Comment by BackMountainDevil** [comment]
ops. It seems that I don't need to open a new one

**Comment by jd1378** [comment]
Hi
yeah you don't need to open a new one
just make add a commit and push, it will be added to the PR

**Comment by jd1378** [comment]
thanks for contributing

**Pull request merged**
