### PR TITLE
Update CodeExtractor.kt

### PR DESCRIPTION
**Pull request by Icarus-Xu**
add keyword sent by alipay

### CODE REVIEW

**Comment by jd1378** [comment]
can this keyword be in other sms/notification that does not contain code ? I'm asking to see if there's going to be false positives or not if we add this

**Comment by jd1378** [comment]
also please take time to add a unit test for it with actual sms message (replace your code with 123456)

**Comment by Icarus-Xu** [comment]
> can this keyword be in other sms/notification that does not contain code ? I'm asking to see if there's going to be false positives or not if we add this

That word is a different chinese expression of "verification code", so I would say no

I will add unit test in the weekend

**Comment by jd1378** [comment]
can you add the unit test so I can merge this ? 
I want to make a release soon

**Comment by jd1378** [comment]
if you copy the message here I can add the unit test myself after merging this

**Comment by Icarus-Xu** [comment]
done, sorry for the delay, things came up.

**Comment by jd1378** [comment]
np, thanks for adding the test

**Comment by Icarus-Xu** [comment]
uh, i guess i made a mistake when pushing, I'm redoing this pr.

**Comment by jd1378** [comment]
I'm not sure if it's your fault though, but it would be nice if you could check why it's failing

**Comment by Icarus-Xu** [comment]
XD, plz check #41 for new PR.

**Pull request closed without merging**
