### PR TITLE
feat: add Chinese(zh-Hans) translation

### PR DESCRIPTION
**Pull request by BackMountainDevil**
according your contribute guide, along `app/src/main/res/values`, I mkdir `app/src/main/res/values-zh-Hans`, and then copy the string.xml. translate it at the last. Try build and got an error "Invalid resource directory name". 

Then the android studio open an excel-like editor(Translations Editor), I add my homeland language(try add zh-Hans but I can not). And copy the translation done before. Tested on virtual machine Nexus S API 30.

After serverl times test, I found there is no a language choice to Chinese, so I edit `LanguageSelectionViewModel.kt` to add a new one. Tested well.

I find another problem when testing, see issue

ps: `test_notification_content` I translate it to a almost real sms code in our life.

### CODE REVIEW

**Comment by jd1378** [comment]
it would be nice if you could also add fastlane metadata for it, which would be shown on f-droid to chinese users

that's not mandatory though

**Comment by jd1378** [comment]
I'll merge and try to change it back to zh-hans

**Comment by jd1378** [comment]
needed to use "values-b+zh+Hans" as resource folder name

**Comment by jd1378** [comment]
thanks for contributing!

**Comment by BackMountainDevil** [comment]
> it would be nice if you could also add fastlane metadata for it, which would be shown on f-droid to chinese users
> 
> that's not mandatory though

I am not familiar with fastlane metadata. If it is a translation, I can do that. Just green hand to Android development.

**Comment by BackMountainDevil** [comment]
> needed to use "values-b+zh+Hans" as resource folder name

Thanks for you kindly work. Chinese has some different languages, similiar but little difference. such as zh-Hans, zh-Hant.

I use zh-Hans most times. I can get the meaning of  zh-Hant but I can not write. So it need to some one else to do with zh-Hant.

**Comment by jd1378** [comment]
I see
Thanks for the explanation

 Im pretty new myself, i just searched about adding zh-Hans

The fast lane metadata i was talking about were these other files i have mentioned in this pinned issue: 
 https://github.com/jd1378/otphelper/issues/10

**Pull request merged**
